### ISSUE TITLE
fluid density problem in input2d file

### ISSUE THREAD

**Issue by 284546C** [nickabattista/IB2d#16]
I am using your ib2d software package for related research work, and I admire you very much for writing such an outstanding program for the study of fluid behavior and making it public. In the process of using, I have a problem and would like to consult you: The fluid density provided in the input2d file is two-dimensional density. Is its value consistent with the density of the material in the three-dimensional state, or does it need to be converted accordingly? Hope to get your reply, thank you

**Comment by nickabattista** [comment]
Thank you for your kind words and interest. The density in the input2d file is actually the regular three-dimensional density. If you're referring an input2d files saying the density's units are "kg/m^2", it is a typo. Thanks!
