### ISSUE TITLE
Regarding the example of Skeleton

### ISSUE THREAD

**Issue by rohitroxkp7** [nickabattista/IB2d#22]
Hello @nickabattista 
I was performing a simulation of the Skeleton example where a rubber band oscillates from a position of non-equilibrium to a position of equilibrium in space and time as the fluid damps the oscillation.
I closed the end point where fluid was being let in. When I ran the simulation, Ib2d threw an error out saying BLOW UP!, Forces are too large. 
I thought this is happening because only springs were in the model. Hence I included beams as well. I toggled the values of almost all the variables such as fluid density, viscosity, elastic constants, etc. Nothing really seems to work. 
Why is this happening?

**Comment by rohitroxkp7** [comment]
> 

I also noticed that there is a problem in Ib2d creating completely closed surfaces and moving them using updating algorithms when running the simulation.

**Comment by nickabattista** [comment]
I'm not sure I follow your issue, as the rubberband is closed already and does not have any 'holes' in it, if you're inquiring about the rubberband example found here: https://github.com/nickabattista/IB2d/tree/master/matIB2d/Examples/Example_Skeleton

What are examples are you referring to here when you say:  _I also noticed that there is a problem in Ib2d creating completely closed surfaces and moving them using updating algorithms when running the simulation_? I have not run into this issue before.

Please attach your rubberband files so I can diagnose your issue. Thanks.

**Comment by rohitroxkp7** [comment]
In the "Give me immersed boundary geometry" function, I just added a line that makes the last point the same as the first point. If you are saying that the rubber band is closed, in terms of springs it is. I just wanted to simulate what it would look like if there was no fluid inside the boundary. Let us say we have a closed body of a fish swimming through water. The region inside the fish body's boundary should not have any fluid. To see if that is possible I started off with the rubber band example. 

[files.zip](https://github.com/nickabattista/IB2d/files/8851529/files.zip)

**Comment by rohitroxkp7** [comment]
Perhaps the forces generated are too high because no fluid inside would mean a lot of hydrostatic pressure on the boundaries

**Comment by nickabattista** [comment]
Unfortunately, the current implementation of IB2d puts the fluid everywhere on the background Eulerian grid; it's based off of Peskin's 2002 IB implementation that does not distinguish between grid points "inside" or "outside" of an immersed body. You might want to take a look at [IBAMR](https://ibamr.github.io/about). It may have what you're looking for? (also see [recent publications from IBAMR](https://ibamr.github.io/publications) to get a better idea of what it's been used for.

**Comment by rohitroxkp7** [comment]
Okay, thanks a ton!
