### ISSUE TITLE
Trouble with new IBM_Driver

### ISSUE THREAD

**Issue by deleeke** [nickabattista/IB2d#6]
@nickabattista @mountaindust 

I had gotten a few simulations with multiple cylinders based off the VIV cylinder example running with the version of the IBM driver from 
this commit:

` fdbf3f0ffeb2df6d6a8950b9df320999c13c7c5b`

But then I merged back in your changes from recently and when I attempt to run the examples, I get this error:

```

 |****** Prepping Immersed Boundary Simulation ******|


--> Reading input data for simulation...

Index exceeds matrix dimensions.

Error in IBM_Driver (line 98)
boussinesq_Yes = model_Info(20);       % Boussinesq Approx.: 0 (for no) or 1 (for yes)

Error in main2d (line 100)
[X, Y, U, V, xLags, yLags] = IBM_Driver(struct_name, mu, rho, grid_Info, dt, T_final, model_Info);
```

What more information would you like from me about this?
[Here are the examples which run with the old IBM_Driver (on a branch using the old IBM_Driver).](https://github.com/deleeke/IB2d/tree/oldIBMDriver/matIB2d/Examples/Example_VIV_Cylinder/MultiCylinder)

**Comment by nickabattista** [comment]
Please do the following:

1. use an updated main2d.m file (it should be in any example folder -> just make sure the path to the IBM_Blackbox is correct (around line 100)

2. add the following two lines in YOUR input2d files directly under "update_damp_springs = 0 ..."
boussinesq = 0          % 0 (for no) or 1 (for yes)  % FOR BOUSSINESQ APPROXIMATION!
expansion_coeff = 1.0   % expansion coefficient for Boussinesq approx.

Thanks
